spring:
  profiles:
    active: local
  application:
    name: rong-ai-code-monther-backend
  session:
    store-type: redis
    timeout: 2592000
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://x.x.x.x:xxxx/rong_ai_code_monther
    username: xxx
    password: xxx
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rong.rongaicodemonther.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: xxxxxxxxxxxxxxxxxxxx
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
#      strict-json-schema: true
#      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: xxxxxxxxxxxxxx
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name